version: '3'
services:
  scada:
    build:
      context: .
      dockerfile: DockerfileJava
      args:
        PORT: 7000
        SERVICE: scada
    ports:
      - "7000:7000"
    network_mode: host
    environment:
      - inDocker=1

  mes:
    build:
      context: .
      dockerfile: DockerfileJava
      args:
        PORT: 7001
        SERVICE: mes
    ports:
      - "7001:7001"
    network_mode: host
    environment:
      - inDocker=1
    depends_on:
      - scada

  erp:
    build:
      context: .
      dockerfile: DockerfileJava
      args:
        PORT: 7002
        SERVICE: erp
    ports:
      - "7002:7002"
    network_mode: host
    environment:
      - inDocker=1
    depends_on:
      - mes
      - scada
